/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("aprender?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cliente c");
        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tel_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cadastrar_btn = new javax.swing.JButton();
        sair_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cod_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nome2_txt = new javax.swing.JTextField();
        email2_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tel2_txt = new javax.swing.JTextField();
        consultar_btn = new javax.swing.JButton();
        alterar_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cod2_txt = new javax.swing.JTextField();
        excluir_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ticket_btn = new javax.swing.JButton();
        atestado_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        jLabel1.setText("NOME:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(22, 37, 50, 30);
        jPanel2.add(nome_txt);
        nome_txt.setBounds(66, 44, 290, 20);

        jLabel2.setText("EMAIL:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(24, 90, 40, 20);
        jPanel2.add(email_txt);
        email_txt.setBounds(70, 90, 280, 20);

        jLabel3.setText("TELEFONE:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 130, 70, 20);
        jPanel2.add(tel_txt);
        tel_txt.setBounds(90, 130, 260, 20);

        jLabel4.setText("AGENDA");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 10, 50, 14);

        cadastrar_btn.setText("CADASTRAR");
        cadastrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(cadastrar_btn);
        cadastrar_btn.setBounds(70, 200, 110, 30);

        sair_btn.setText("SAIR");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });
        jPanel2.add(sair_btn);
        sair_btn.setBounds(230, 200, 80, 30);

        jTabbedPane1.addTab("Cadastrar", jPanel2);

        jPanel3.setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, clienteList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliCod}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliNome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliEmail}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliTel}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(Long.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 390, 80);

        jLabel5.setText("Código:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 90, 70, 20);

        cod_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_txtActionPerformed(evt);
            }
        });
        jPanel3.add(cod_txt);
        cod_txt.setBounds(70, 90, 260, 20);

        jLabel6.setText("Nome:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(21, 120, 40, 20);

        jLabel7.setText("Email:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 150, 60, 20);

        nome2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome2_txtActionPerformed(evt);
            }
        });
        jPanel3.add(nome2_txt);
        nome2_txt.setBounds(70, 120, 260, 20);

        email2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email2_txtActionPerformed(evt);
            }
        });
        jPanel3.add(email2_txt);
        email2_txt.setBounds(70, 150, 260, 20);

        jLabel8.setText("Telefone:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 180, 90, 20);
        jPanel3.add(tel2_txt);
        tel2_txt.setBounds(70, 180, 260, 20);

        consultar_btn.setText("Consultar");
        consultar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_btnActionPerformed(evt);
            }
        });
        jPanel3.add(consultar_btn);
        consultar_btn.setBounds(40, 220, 120, 40);

        alterar_btn.setText("Alterar");
        alterar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_btnActionPerformed(evt);
            }
        });
        jPanel3.add(alterar_btn);
        alterar_btn.setBounds(220, 220, 110, 40);

        jTabbedPane1.addTab("Consultar/Alterar", jPanel3);

        jPanel4.setLayout(null);

        jLabel9.setText("CÓDIGO:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(160, 50, 60, 30);

        cod2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod2_txtActionPerformed(evt);
            }
        });
        jPanel4.add(cod2_txt);
        cod2_txt.setBounds(110, 90, 170, 20);

        excluir_btn.setText("Excluir");
        excluir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_btnActionPerformed(evt);
            }
        });
        jPanel4.add(excluir_btn);
        excluir_btn.setBounds(120, 130, 120, 30);

        jTabbedPane1.addTab("Excluir", jPanel4);

        jPanel1.setLayout(null);

        ticket_btn.setText("TICKET");
        ticket_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticket_btnActionPerformed(evt);
            }
        });
        jPanel1.add(ticket_btn);
        ticket_btn.setBounds(140, 50, 120, 23);

        atestado_btn.setText("ATESTADOS");
        atestado_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atestado_btnActionPerformed(evt);
            }
        });
        jPanel1.add(atestado_btn);
        atestado_btn.setBounds(140, 130, 120, 23);

        jButton3.setText("jButton3");
        jPanel1.add(jButton3);
        jButton3.setBounds(169, 210, 73, 23);

        jTabbedPane1.addTab("Relatório", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void excluir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_btnActionPerformed
        String x = JOptionPane.showInputDialog(null, "Deseja Apagar Registros? \n 1- sim \n 2- não");
        int op = Integer.parseInt(x);
        if (op == 1) {
            Controller.Funcoes_DAO.excluir();
        } else {
            JOptionPane.showMessageDialog(null, "Exclusão Cancelada");
        }
    }//GEN-LAST:event_excluir_btnActionPerformed

    private void cod2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod2_txtActionPerformed

    private void alterar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_btnActionPerformed
        Controller.Funcoes_DAO.alterar();
    }//GEN-LAST:event_alterar_btnActionPerformed

    private void consultar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_btnActionPerformed
        Controller.Funcoes_DAO.consultar();
    }//GEN-LAST:event_consultar_btnActionPerformed

    private void email2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email2_txtActionPerformed

    private void nome2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome2_txtActionPerformed

    private void cod_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_txtActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_btnActionPerformed

    private void cadastrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_btnActionPerformed
        Controller.Funcoes_DAO.cadastrar();
    }//GEN-LAST:event_cadastrar_btnActionPerformed

    private void ticket_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticket_btnActionPerformed
        Controller.Ticket_DAO.impressao();
    }//GEN-LAST:event_ticket_btnActionPerformed

    private void atestado_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atestado_btnActionPerformed
        try {
            Controller.Press_DAO.imprime();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atestado_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar_btn;
    public static javax.swing.JButton atestado_btn;
    private javax.swing.JButton cadastrar_btn;
    private java.util.List<View.Cliente> clienteList;
    private javax.persistence.Query clienteQuery;
    public static javax.swing.JTextField cod2_txt;
    public static javax.swing.JTextField cod_txt;
    private javax.swing.JButton consultar_btn;
    public static javax.swing.JTextField email2_txt;
    public static javax.swing.JTextField email_txt;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton excluir_btn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField nome2_txt;
    public static javax.swing.JTextField nome_txt;
    private javax.swing.JButton sair_btn;
    public static javax.swing.JTextField tel2_txt;
    public static javax.swing.JTextField tel_txt;
    public static javax.swing.JButton ticket_btn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
